"""
Attribution testing for Experiment 0.

For each (evaluator, source, prompt) triple, present the evaluator with a
conversation whose assistant turn was generated by source, then ask whether
the evaluator recognises it as its own output.

Output:
  results_dir/attribution_results.json  — list of result dicts
  results_dir/attribution_results.csv   — same as CSV
"""

import json
import time
from pathlib import Path

import pandas as pd
from tqdm import tqdm

from .config import Experiment0Config
from .utils import api_call_with_retry, make_client

_COST_LOG_EVERY = 100


def run_all_attribution(
    prompts: list[dict],
    responses: list[dict],
    config: Experiment0Config,
    force: bool = False,
) -> list[dict]:
    out_json = config.results_dir / "attribution_results.json"
    out_csv = config.results_dir / "attribution_results.csv"

    # Build fast response lookup: prompt_id → {model_key: text}
    resp_lookup: dict[str, dict[str, str]] = {
        r["prompt_id"]: r["responses"] for r in responses
    }

    # Load existing results for checkpoint/resume
    existing_results: list[dict] = []
    if out_json.exists() and not force:
        with open(out_json) as f:
            existing_results = json.load(f)

    completed: set[tuple] = {
        (r["evaluator"], r["source"], r["prompt_id"])
        for r in existing_results
    }
    print(f"  {len(completed)} attribution calls already completed.")

    results = list(existing_results)
    client = make_client(config)
    running_cost = 0.0
    n_calls_since_log = 0

    model_keys = list(config.models.keys())
    total = len(model_keys) ** 2 * len(prompts)
    remaining = total - len(completed)
    print(f"  {remaining} calls remaining ({total} total).")

    with tqdm(total=remaining, desc="Attribution") as pbar:
        for eval_key, eval_id in config.models.items():
            for src_key in model_keys:
                for prompt in prompts:
                    pid = prompt["prompt_id"]
                    key = (eval_key, src_key, pid)
                    if key in completed:
                        continue

                    src_response = resp_lookup.get(pid, {}).get(src_key, "")
                    if not src_response:
                        pbar.update(1)
                        continue

                    messages = _build_messages(
                        eval_key, config, prompt["instruction"], src_response
                    )

                    def _call():
                        return client.chat.completions.create(
                            model=eval_id,
                            messages=messages,
                            temperature=0.0,
                            max_tokens=config.max_tokens_attribution,
                        )

                    response = api_call_with_retry(
                        _call,
                        max_retries=config.max_retries,
                        retry_delay=config.retry_delay,
                    )

                    choices = getattr(response, "choices", None) if response else None
                    raw = choices[0].message.content if choices else ""
                    parsed = parse_attribution(raw)

                    # Cost tracking for paid models
                    if eval_key in config.paid_model_keys and response and response.usage:
                        u = response.usage
                        cost = (
                            u.prompt_tokens * config.cost_input_per_token.get(eval_key, 0)
                            + u.completion_tokens * config.cost_output_per_token.get(eval_key, 0)
                        )
                        running_cost += cost
                        n_calls_since_log += 1
                        if n_calls_since_log >= _COST_LOG_EVERY:
                            print(f"\n  Running cost: ${running_cost:.4f}")
                            n_calls_since_log = 0
                        if running_cost > config.cost_warning_threshold:
                            print(
                                f"\n  WARNING: running cost ${running_cost:.4f} exceeds "
                                f"threshold ${config.cost_warning_threshold:.2f}. Continuing..."
                            )

                    record = {
                        "prompt_id": pid,
                        "dataset": prompt["dataset"],
                        "evaluator": eval_key,
                        "source": src_key,
                        "is_self": eval_key == src_key,
                        "raw_response": raw,
                        "parsed": parsed,
                    }
                    results.append(record)
                    completed.add(key)

                    # Incremental save every 50 new results
                    if len(results) % 50 == 0:
                        _save(results, out_json, out_csv)

                    delay = config.get_delay(eval_key)
                    time.sleep(delay)
                    pbar.update(1)

    _save(results, out_json, out_csv)
    print(f"\n  Total cost (paid models): ${running_cost:.4f}")
    _report_unparseable(results, config)
    return results


def _build_messages(
    eval_key: str,
    config: Experiment0Config,
    instruction: str,
    src_response: str,
) -> list[dict]:
    use_system = eval_key not in config.no_system_message_models
    msgs = []
    if use_system:
        msgs.append({"role": "system", "content": "You are a helpful assistant."})
    msgs += [
        {"role": "user", "content": instruction},
        {"role": "assistant", "content": src_response},
        {"role": "user", "content": config.attribution_prompt},
    ]
    return msgs


def parse_attribution(text: str) -> str:
    """Returns 'me', 'not_me', or 'unparseable'."""
    t = text.strip().lower()
    if "answer: not me" in t:
        return "not_me"
    if "answer: me" in t:
        return "me"
    if "not me" in t:
        return "not_me"
    if t in ("me", '"me"', "'me'"):
        return "me"
    return "unparseable"


def _save(results: list[dict], json_path: Path, csv_path: Path) -> None:
    with open(json_path, "w") as f:
        json.dump(results, f, indent=2)
    pd.DataFrame(results).to_csv(csv_path, index=False)


def _report_unparseable(results: list[dict], config: Experiment0Config) -> None:
    df = pd.DataFrame(results)
    print("\n  Unparseable rate by evaluator:")
    for eval_key in config.models:
        sub = df[df["evaluator"] == eval_key]
        if len(sub) == 0:
            continue
        rate = (sub["parsed"] == "unparseable").mean()
        print(f"    {eval_key}: {rate:.1%}")
        if rate > 0.10:
            print(f"      WARNING: unparseable rate > 10% for {eval_key}. Consider revising prompt.")
